app:
    accent: duck
    minimize_to_tray: true
    theme: dark
database:
    dsn: tasks.db
    type: sqlite
pomodoro:
    long_break: 15
    sessions_before_long: 4
    short_break: 5
    work_duration: 25
