// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDailyActivity(arg1) {
  return window['go']['main']['App']['GetDailyActivity'](arg1);
}

export function GetLaunchOnStartup() {
  return window['go']['main']['App']['GetLaunchOnStartup']();
}

export function GetSessionsForTask(arg1) {
  return window['go']['main']['App']['GetSessionsForTask'](arg1);
}

export function GetTasksByStatus(arg1) {
  return window['go']['main']['App']['GetTasksByStatus'](arg1);
}

export function GetTimerState() {
  return window['go']['main']['App']['GetTimerState']();
}

export function GetTodayStats() {
  return window['go']['main']['App']['GetTodayStats']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function ImportData(arg1) {
  return window['go']['main']['App']['ImportData'](arg1);
}

export function ReorderTasks(arg1) {
  return window['go']['main']['App']['ReorderTasks'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveWindowPosition() {
  return window['go']['main']['App']['SaveWindowPosition']();
}

export function SetLaunchOnStartup(arg1) {
  return window['go']['main']['App']['SetLaunchOnStartup'](arg1);
}

export function StartPomodoro(arg1, arg2) {
  return window['go']['main']['App']['StartPomodoro'](arg1, arg2);
}

export function StopPomodoro() {
  return window['go']['main']['App']['StopPomodoro']();
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
