// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';
import {config} from '../models';
import {services} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CreateTask(arg1:models.Task):Promise<models.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function ExportData():Promise<string>;

export function GetAllTasks():Promise<Array<models.Task>>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetDailyActivity(arg1:number):Promise<Array<services.DailyActivity>>;

export function GetLaunchOnStartup():Promise<boolean>;

export function GetSessionsForTask(arg1:number):Promise<Array<models.PomodoroSession>>;

export function GetTasksByStatus(arg1:string):Promise<Array<models.Task>>;

export function GetTimerState():Promise<services.TimerState>;

export function GetTodayStats():Promise<services.PomodoroStats>;

export function HideToTray():Promise<void>;

export function ImportData(arg1:string):Promise<services.ImportResult>;

export function ReorderTasks(arg1:Array<number>):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveWindowPosition():Promise<void>;

export function SetLaunchOnStartup(arg1:boolean):Promise<void>;

export function StartPomodoro(arg1:number,arg2:string):Promise<void>;

export function StopPomodoro():Promise<void>;

export function TestConnection(arg1:string,arg2:string):Promise<void>;

export function UpdateTask(arg1:models.Task):Promise<models.Task>;
